from __future__ import annotations

import asyncio
import json
import time
from typing import Any
from urllib.parse import urlsplit
from uuid import uuid4

import httpx


class SplunkMCPError(RuntimeError):
    pass


TOOL_ALIASES: dict[str, list[str]] = {
    "run_query": ["splunk_run_query", "run_splunk_query", "run_query"],
    "get_info": ["splunk_get_info", "get_splunk_info", "server_info"],
    "get_indexes": ["splunk_get_indexes", "get_indexes", "list_indexes"],
    "get_metadata": ["splunk_get_metadata", "get_metadata", "metadata"],
    "get_users": ["splunk_get_user_info", "splunk_get_user_list", "get_user_list"],
    "get_knowledge_objects": ["splunk_get_knowledge_objects", "get_knowledge_objects"],
    "generate_spl": ["saia_generate_spl", "generate_spl"],
    "explain_spl": ["saia_explain_spl", "explain_spl"],
    "optimize_spl": ["saia_optimize_spl", "optimize_spl"],
}

CACHEABLE_TOOLS = {
    "get_info",
    "get_indexes",
    "get_metadata",
    "get_users",
    "get_knowledge_objects",
    "splunk_get_kv_store_collections",
}


class SplunkMCPClient:
    """Streamable HTTP MCP client tolerant of common Splunk tool naming variants."""

    def __init__(
        self,
        url: str,
        token: str = "",
        verify_ssl: bool = True,
        ca_bundle: str | None = None,
        cache_ttl: float = 30,
        timeout: float = 120,
    ):
        self.url = url.rstrip("/")
        self.token = token
        self.verify_ssl = ca_bundle if verify_ssl and ca_bundle else verify_ssl
        self._tools: list[dict[str, Any]] | None = None
        self._initialized = False
        self._session_id = ""
        self.server_info: dict[str, Any] = {}
        self.cache_ttl = cache_ttl
        self.timeout = timeout
        self._cache: dict[str, tuple[float, Any]] = {}
        self._init_lock = asyncio.Lock()
        self._tools_lock = asyncio.Lock()

    def _headers(self) -> dict[str, str]:
        headers = {
            "Accept": "application/json, text/event-stream",
            "Content-Type": "application/json",
        }
        if self.token:
            headers["Authorization"] = f"Bearer {self.token}"
        if self._session_id:
            headers["Mcp-Session-Id"] = self._session_id
        return headers

    def _http_error(self, exc: httpx.HTTPStatusError) -> SplunkMCPError:
        status = exc.response.status_code
        path = urlsplit(self.url).path.rstrip("/")
        if status == 405 and path == "/service/mcp":
            detail = "The Splunk MCP path is /services/mcp (plural), not /service/mcp."
        elif status == 405:
            detail = (
                "This URL does not accept MCP POST requests. Copy the exact endpoint from the "
                "Splunk MCP Server app; the usual Splunk Enterprise path is /services/mcp."
            )
        elif status in {401, 403}:
            detail = (
                "Authentication was rejected. Use the encrypted token generated by the Splunk MCP "
                "Server app, and confirm the user role has mcp_tool_execute."
            )
        elif status == 404:
            detail = "MCP endpoint not found. Copy the endpoint shown in the Splunk MCP Server app."
        else:
            detail = f"The MCP endpoint returned HTTP {status}."
        return SplunkMCPError(detail)

    @staticmethod
    def _decode_response(response: httpx.Response) -> dict[str, Any]:
        if response.status_code == 202 or not response.content:
            return {}
        if "text/event-stream" in response.headers.get("content-type", ""):
            data_lines = [line[5:].strip() for line in response.text.splitlines() if line.startswith("data:")]
            return json.loads(data_lines[-1]) if data_lines else {}
        return response.json()

    async def _post(self, payload: dict[str, Any]) -> dict[str, Any]:
        if not self.url:
            raise SplunkMCPError("Splunk MCP URL is not configured")
        try:
            async with httpx.AsyncClient(verify=self.verify_ssl, timeout=self.timeout) as client:
                response = await client.post(self.url, headers=self._headers(), json=payload)
                response.raise_for_status()
                session_id = response.headers.get("Mcp-Session-Id")
                if session_id:
                    self._session_id = session_id
                return self._decode_response(response)
        except httpx.HTTPStatusError as exc:
            raise self._http_error(exc) from exc
        except (httpx.HTTPError, ValueError, json.JSONDecodeError) as exc:
            raise SplunkMCPError(f"Unable to reach the Splunk MCP endpoint: {exc}") from exc

    async def _ensure_initialized(self) -> None:
        if self._initialized:
            return
        async with self._init_lock:
            if self._initialized:
                return
            payload = {
                "jsonrpc": "2.0",
                "id": str(uuid4()),
                "method": "initialize",
                "params": {
                    "protocolVersion": "2025-03-26",
                    "capabilities": {},
                    "clientInfo": {"name": "SignalRoom", "version": "0.1.0"},
                },
            }
            data = await self._post(payload)
            if data.get("error"):
                error = data["error"]
                raise SplunkMCPError(error.get("message", str(error)))
            result = data.get("result", data)
            self.server_info = result.get("serverInfo", {}) if isinstance(result, dict) else {}
            await self._post({"jsonrpc": "2.0", "method": "notifications/initialized"})
            self._initialized = True

    async def _request(self, method: str, params: dict[str, Any]) -> dict[str, Any]:
        await self._ensure_initialized()
        payload = {"jsonrpc": "2.0", "id": str(uuid4()), "method": method, "params": params}
        data = await self._post(payload)
        if data.get("error"):
            error = data["error"]
            raise SplunkMCPError(error.get("message", str(error)))
        return data.get("result", data)

    async def list_tools(self, refresh: bool = False) -> list[dict[str, Any]]:
        if self._tools is not None and not refresh:
            return self._tools
        async with self._tools_lock:
            if self._tools is not None and not refresh:
                return self._tools
            result = await self._request("tools/list", {})
            tools = result.get("tools", []) if isinstance(result, dict) else []
            if not tools and isinstance(result, dict):
                for item in result.get("content", []):
                    try:
                        parsed = json.loads(item.get("text", ""))
                        tools.extend(parsed.get("tools", []))
                    except (AttributeError, json.JSONDecodeError):
                        continue
            self._tools = tools
            return tools

    async def resolve(self, logical_name: str) -> str:
        tools = await self.list_tools()
        names = {tool.get("name") for tool in tools}
        for candidate in TOOL_ALIASES.get(logical_name, [logical_name]):
            if candidate in names:
                return candidate
        raise SplunkMCPError(f"No compatible MCP tool found for '{logical_name}'")

    async def call(self, logical_name: str, arguments: dict[str, Any] | None = None) -> Any:
        arguments = arguments or {}
        cache_key = json.dumps([logical_name, arguments], sort_keys=True, default=str)
        if logical_name in CACHEABLE_TOOLS and self.cache_ttl > 0:
            cached = self._cache.get(cache_key)
            if cached and time.monotonic() - cached[0] < self.cache_ttl:
                return cached[1]
        name = await self.resolve(logical_name)
        result = await self._request("tools/call", {"name": name, "arguments": arguments})
        normalized = self.normalize_result(result)
        if logical_name in CACHEABLE_TOOLS and self.cache_ttl > 0:
            self._cache[cache_key] = (time.monotonic(), normalized)
        return normalized

    async def health(self) -> dict[str, Any]:
        try:
            tools = await self.list_tools(refresh=True)
            return {
                "ok": True,
                "tool_count": len(tools),
                "tools": [item.get("name") for item in tools],
                "server": self.server_info,
            }
        except SplunkMCPError as exc:
            return {"ok": False, "error": str(exc), "tool_count": 0, "tools": []}

    @staticmethod
    def normalize_result(result: Any) -> Any:
        if not isinstance(result, dict):
            return result
        if result.get("isError"):
            texts = [item.get("text", "") for item in result.get("content", []) if isinstance(item, dict)]
            raise SplunkMCPError("\n".join(texts) or "Splunk MCP tool returned an error")
        content = result.get("content")
        if not isinstance(content, list):
            return result
        values: list[Any] = []
        for item in content:
            if not isinstance(item, dict):
                continue
            text = item.get("text")
            if not isinstance(text, str):
                values.append(item)
                continue
            try:
                values.append(json.loads(text))
            except json.JSONDecodeError:
                values.append(text)
        return values[0] if len(values) == 1 else values
